spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/sse
    #username: postgres
    #password:
    #driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aitutour.postgres.database.azure.com:5432/aitutour?sslmode=require
    username: sse
    password: 1234567890Q!
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: memo.redis.cache.windows.net
      port: 6380
      ssl:
        enabled: true
      password: oOC4rSC3SUnEDGyzastqAIMSYQgdBygTFAzCaClWls4=

# rabbitmq:
  # host: 20.90.119.245
  # port: 5672
  # username: guest
  # password: guest

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      platform: postgres

  # max file size for uploading
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    enabled: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.jdbcTransactionManager: debug

JwtUtils:
  secretKey: VrGwQxOdlnd6df60d07ZlrHN1f58ChWZ4stzoMeq2Ts
  expiration: 604800



